/* EZO STİLE v2 - System Configuration, Constants & Full 5-Language i18n Engine */

export const CONFIG = {
  APP_NAME: 'EZO STİLE v2',
  APP_VERSION: '2.0.0',
  FIREBASE_DB_URL: 'https://ezostile-barber-default-rtdb.europe-west1.firebasedatabase.app',
  ROLE_HIERARCHY: ['super_admin', 'owner', 'manager', 'barber', 'receptionist', 'customer'],
  ROLE_LABELS: {
    super_admin: '⚡ Platform Süper Admin',
    owner: '👑 Salon Sahibi / Owner',
    manager: '🧑‍💼 Yönetici / Manager',
    barber: '💈 Berber Uzmanı / Barber',
    receptionist: '🛎️ Resepsiyonist',
    customer: '👤 Müşteri'
  },
  DEFAULT_BUSINESS_ID: 'biz_merkez_salon'
};

export const SUPPORTED_LANGUAGES = [
  { code: 'tr', name: 'Türkçe', flag: '🇹🇷', dir: 'ltr' },
  { code: 'en', name: 'English', flag: '🇬🇧', dir: 'ltr' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺', dir: 'ltr' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦', dir: 'rtl' },
  { code: 'tk', name: 'Türkmençe', flag: '🇹🇲', dir: 'ltr' }
];

export function detectDefaultLanguage() {
  if (typeof window === 'undefined') return 'tr';
  const saved = localStorage.getItem('ezo_lang');
  if (saved && ['tr', 'en', 'ru', 'ar', 'tk'].includes(saved)) return saved;
  
  const navLang = (navigator.language || 'tr').toLowerCase();
  if (navLang.startsWith('en')) return 'en';
  if (navLang.startsWith('ru')) return 'ru';
  if (navLang.startsWith('ar')) return 'ar';
  if (navLang.startsWith('tk') || navLang.startsWith('tm')) return 'tk';
  return 'tr';
}

export function isRtl(lang) {
  return lang === 'ar';
}

export const DICTIONARY = {
  tr: {
    welcomeTitle: 'EZO STİLE v2',
    welcomeSub: 'VIP Berber & Güzellik Platformu',
    imCustomer: '👤 Müşteriyim',
    iHaveSalon: '💈 Salonum Var',
    customerLoginTitle: '👤 Müşteri Girişi / Kayıt',
    salonLoginTitle: '🔑 Salon Girişi',
    salonApplyTitle: '📋 Yeni Salon Başvurusu',
    staffInviteTitle: '🎟️ Çalışan Davet Kodum Var',
    phoneLabel: 'Telefon Numaranız',
    passwordLabel: 'Şifreniz',
    nameLabel: 'Adınız Soyadınız',
    salonNameLabel: 'Salon Adı',
    cityLabel: 'Şehir',
    districtLabel: 'İlçe',
    addressLabel: 'Adres Detayı',
    loginBtn: 'Giriş Yap',
    registerBtn: 'Kayıt Ol',
    applyBtn: 'Başvuru Gönder',
    pendingApprovalMsg: 'Başvurunuz Süper Admin onayı bekliyor.',
    noSalonAccountMsg: 'Bu telefon numarasına bağlı salon hesabı bulunamadı.',
    homeTab: 'Ana Sayfa',
    salonsTab: 'Keşfet',
    bookingTab: 'Randevu Al',
    appointmentsTab: 'Randevularım',
    aiTab: 'AI',
    profileTab: 'Profil',
    managementTab: 'Yönetim',
    calendarTab: 'Takvim',
    dashboardTab: 'Panel',
    bookAppointment: '✂️ Randevu Al',
    discoverSalons: '💈 Salonları Keşfet',
    aiConsultant: '🤖 AI Saç Danışmanı',
    myAppointments: '📅 Randevularım',
    selectServiceBtn: 'Hizmet Seç ▼',
    selectedService: 'Seçilen Hizmet',
    selectStaff: 'Berber / Uzman Seçin',
    selectDateTime: 'Tarih ve Saat Seçin',
    confirmBooking: '⚡ Randevuyu Onayla',
    notifyWhatsApp: '💬 WhatsApp ile Bildir',
    notifySms: '📱 SMS ile Bildir',
    notNow: '❌ Şimdi Değil',
    cancelAppointment: '❌ İptal Et',
    rescheduleAppointment: '🔄 Tarih/Saat Değiştir',
    pending: 'BEKLEYEN',
    approved: 'ONAYLANDI',
    completed: 'TAMAMLANDI',
    rejected: 'REDDEDİLDİ',
    cancelled: 'İPTAL EDİLDİ',
    reschedule_requested: 'TARİH DEĞİŞİKLİĞİ İSTENDİ',
    no_show: 'GELMEDİ',
    today: 'Bugün',
    tomorrow: 'Yarın',
    selectDate: '📅 Tarih Seç',
    language: 'Dil / Language',
    logout: 'Çıkış Yap',
    profileTitle: '👤 Müşteri Profili',
    notificationSettings: '🔔 Bildirim Ayarları',
    privacyAccount: '🔒 Gizlilik / Hesap',
    helpSupport: '💬 Yardım & Destek',
    closeBtn: 'Kapat',
    saveBtn: 'Kaydet',
    confirmTitle: 'Onay',
    successTitle: 'Başarılı',
    errorTitle: 'Hata'
  },
  en: {
    welcomeTitle: 'EZO STİLE v2',
    welcomeSub: 'VIP Barber & Beauty Platform',
    imCustomer: '👤 I am a Customer',
    iHaveSalon: '💈 I Have a Salon',
    customerLoginTitle: '👤 Customer Login / Register',
    salonLoginTitle: '🔑 Salon Owner Login',
    salonApplyTitle: '📋 New Salon Application',
    staffInviteTitle: '🎟️ I Have a Staff Invite Code',
    phoneLabel: 'Phone Number',
    passwordLabel: 'Password',
    nameLabel: 'Full Name',
    salonNameLabel: 'Salon Name',
    cityLabel: 'City',
    districtLabel: 'District',
    addressLabel: 'Address Details',
    loginBtn: 'Log In',
    registerBtn: 'Sign Up',
    applyBtn: 'Submit Application',
    pendingApprovalMsg: 'Your application is awaiting Super Admin approval.',
    noSalonAccountMsg: 'No salon account found for this phone number.',
    homeTab: 'Home',
    salonsTab: 'Discover',
    bookingTab: 'Book Now',
    appointmentsTab: 'Bookings',
    aiTab: 'AI',
    profileTab: 'Profile',
    managementTab: 'Management',
    calendarTab: 'Calendar',
    dashboardTab: 'Dashboard',
    bookAppointment: '✂️ Book Appointment',
    discoverSalons: '💈 Discover Salons',
    aiConsultant: '🤖 AI Hair Consultant',
    myAppointments: '📅 My Bookings',
    selectServiceBtn: 'Select Service ▼',
    selectedService: 'Selected Service',
    selectStaff: 'Select Barber / Staff',
    selectDateTime: 'Select Date & Time',
    confirmBooking: '⚡ Confirm Booking',
    notifyWhatsApp: '💬 Notify via WhatsApp',
    notifySms: '📱 Notify via SMS',
    notNow: '❌ Not Now',
    cancelAppointment: '❌ Cancel',
    rescheduleAppointment: '🔄 Reschedule',
    pending: 'PENDING',
    approved: 'APPROVED',
    completed: 'COMPLETED',
    rejected: 'REJECTED',
    cancelled: 'CANCELLED',
    reschedule_requested: 'RESCHEDULE REQUESTED',
    no_show: 'NO SHOW',
    today: 'Today',
    tomorrow: 'Tomorrow',
    selectDate: '📅 Select Date',
    language: 'Language',
    logout: 'Log Out',
    profileTitle: '👤 Customer Profile',
    notificationSettings: '🔔 Notifications',
    privacyAccount: '🔒 Privacy & Account',
    helpSupport: '💬 Help & Support',
    closeBtn: 'Close',
    saveBtn: 'Save',
    confirmTitle: 'Confirmation',
    successTitle: 'Success',
    errorTitle: 'Error'
  },
  ru: {
    welcomeTitle: 'EZO STİLE v2',
    welcomeSub: 'VIP Платформа для барбершопов',
    imCustomer: '👤 Я Клиент',
    iHaveSalon: '💈 У меня салон',
    customerLoginTitle: '👤 Вход / Регистрация клиента',
    salonLoginTitle: '🔑 Вход для салона',
    salonApplyTitle: '📋 Заявка на салон',
    staffInviteTitle: '🎟️ Код приглашения мастера',
    phoneLabel: 'Номер телефона',
    passwordLabel: 'Пароль',
    nameLabel: 'Имя и Фамилия',
    salonNameLabel: 'Название салона',
    cityLabel: 'Город',
    districtLabel: 'Район',
    addressLabel: 'Адрес',
    loginBtn: 'Войти',
    registerBtn: 'Регистрация',
    applyBtn: 'Отправить заявку',
    pendingApprovalMsg: 'Ваша заявка ожидает подтверждения администратора.',
    noSalonAccountMsg: 'Аккаунт салона не найден для этого номера телефона.',
    homeTab: 'Главная',
    salonsTab: 'Поиск',
    bookingTab: 'Запись',
    appointmentsTab: 'Мои записи',
    aiTab: 'AI',
    profileTab: 'Профиль',
    managementTab: 'Управление',
    calendarTab: 'Календарь',
    dashboardTab: 'Панель',
    bookAppointment: '✂️ Записаться',
    discoverSalons: '💈 Поиск салонов',
    aiConsultant: '🤖 AI Консультант',
    myAppointments: '📅 Мои записи',
    selectServiceBtn: 'Выбрать услугу ▼',
    selectedService: 'Выбранная услуга',
    selectStaff: 'Выберите мастера',
    selectDateTime: 'Выберите дату и время',
    confirmBooking: '⚡ Подтвердить запись',
    notifyWhatsApp: '💬 Уведомить в WhatsApp',
    notifySms: '📱 Уведомить по SMS',
    notNow: '❌ Не сейчас',
    cancelAppointment: '❌ Отменить',
    rescheduleAppointment: '🔄 Перенести',
    pending: 'В ОЖИДАНИИ',
    approved: 'ПОДТВЕРЖДЕНО',
    completed: 'ЗАВЕРШЕНО',
    rejected: 'ОТКЛОНЕНО',
    cancelled: 'ОТМЕНЕНО',
    reschedule_requested: 'ЗАПРОС ПЕРЕНОСА',
    no_show: 'НЕ ЯВИЛСЯ',
    today: 'Сегодня',
    tomorrow: 'Завтра',
    selectDate: '📅 Выбрать дату',
    language: 'Язык',
    logout: 'Выйти',
    profileTitle: '👤 Профиль клиента',
    notificationSettings: '🔔 Уведомления',
    privacyAccount: '🔒 Безопасность',
    helpSupport: '💬 Помощь',
    closeBtn: 'Закрыть',
    saveBtn: 'Сохранить',
    confirmTitle: 'Подтверждение',
    successTitle: 'Успешно',
    errorTitle: 'Ошибка'
  },
  ar: {
    welcomeTitle: 'EZO STİLE v2',
    welcomeSub: 'منصة الصالونات الراقية',
    imCustomer: '👤 أنا عميل',
    iHaveSalon: '💈 لدي صالون',
    customerLoginTitle: '👤 تسجيل دخول العميل',
    salonLoginTitle: '🔑 دخول الصالون',
    salonApplyTitle: '📋 طلب انضمام صالون',
    staffInviteTitle: '🎟️ رمز دعوة موظف',
    phoneLabel: 'رقم الهاتف',
    passwordLabel: 'كلمة المرور',
    nameLabel: 'الاسم الكامل',
    salonNameLabel: 'اسم الصالون',
    cityLabel: 'المدينة',
    districtLabel: 'المنطقة',
    addressLabel: 'العنوان',
    loginBtn: 'تسجيل الدخول',
    registerBtn: 'إنشاء حساب',
    applyBtn: 'إرسال الطلب',
    pendingApprovalMsg: 'طلبك قيد مراجعة الإدارة.',
    noSalonAccountMsg: 'لم يتم العثور على حساب صالون لهذا الرقم.',
    homeTab: 'الرئيسية',
    salonsTab: 'استكشاف',
    bookingTab: 'حجز',
    appointmentsTab: 'مواعيدي',
    aiTab: 'AI',
    profileTab: 'الملف الشخصي',
    managementTab: 'الإدارة',
    calendarTab: 'التقويم',
    dashboardTab: 'اللوحة',
    bookAppointment: '✂️ حجز موعد',
    discoverSalons: '💈 استكشاف الصالونات',
    aiConsultant: '🤖 مستشار الذكاء الاصطناعي',
    myAppointments: '📅 مواعيدي',
    selectServiceBtn: 'اختر الخدمة ▼',
    selectedService: 'الخدمة المختارة',
    selectStaff: 'اختر الحلاق',
    selectDateTime: 'اختر التاريخ والوقت',
    confirmBooking: '⚡ تأكيد الحجز',
    notifyWhatsApp: '💬 إشعار عبر WhatsApp',
    notifySms: '📱 إشعار عبر SMS',
    notNow: '❌ ليس الآن',
    cancelAppointment: '❌ إلغاء',
    rescheduleAppointment: '🔄 تغيير الموعد',
    pending: 'قيد الانتظار',
    approved: 'تم التأكيد',
    completed: 'مكتمل',
    rejected: 'مرفوض',
    cancelled: 'ملغي',
    reschedule_requested: 'طلب تغيير الموعد',
    no_show: 'لم يحضر',
    today: 'اليوم',
    tomorrow: 'غداً',
    selectDate: '📅 اختر التاريخ',
    language: 'اللغة',
    logout: 'تسجيل الخروج',
    profileTitle: '👤 الملف الشخصي',
    notificationSettings: '🔔 الإشعارات',
    privacyAccount: '🔒 الخصوصية',
    helpSupport: '💬 الدعم والمساندة',
    closeBtn: 'إغلاق',
    saveBtn: 'حفظ',
    confirmTitle: 'تأكيد',
    successTitle: 'نجاح',
    errorTitle: 'خطأ'
  },
  tk: {
    welcomeTitle: 'EZO STİLE v2',
    welcomeSub: 'VIP Berber we Gözellik Platformasy',
    imCustomer: '👤 Men Müşderi',
    iHaveSalon: '💈 Salonym Bar',
    customerLoginTitle: '👤 Müşderi Girmek / Agza Bolmak',
    salonLoginTitle: '🔑 Salon Eýesi Girmek',
    salonApplyTitle: '📋 Täze Salon Ýüzlenmesi',
    staffInviteTitle: '🎟️ Işgär Çakylyk Kody',
    phoneLabel: 'Telefon belgisi',
    passwordLabel: 'Açar sözi',
    nameLabel: 'At-Familiýa',
    salonNameLabel: 'Salonyn Ady',
    cityLabel: 'Şäher',
    districtLabel: 'Etrap',
    addressLabel: 'Salgy',
    loginBtn: 'Ulgama Gir',
    registerBtn: 'Agza Bol',
    applyBtn: 'Ýüzlenme Ugrat',
    pendingApprovalMsg: 'Ýüzlenmäňiz Administrator tassyklamagyna garaşýar.',
    noSalonAccountMsg: 'Bu telefon belgisinde salon hesaby tapylmady.',
    homeTab: 'Baş Sahypa',
    salonsTab: 'Gözlemek',
    bookingTab: 'Ýazylmak',
    appointmentsTab: 'Ýazylmalarym',
    aiTab: 'AI',
    profileTab: 'Profil',
    managementTab: 'Dolandyryş',
    calendarTab: 'Kalenar',
    dashboardTab: 'Panel',
    bookAppointment: '✂️ Ýazylmak',
    discoverSalons: '💈 Salonlary Gözlemek',
    aiConsultant: '🤖 AI Saç Maslahatçysy',
    myAppointments: '📅 Ýazylmalarym',
    selectServiceBtn: 'Hyzmat Saýlaň ▼',
    selectedService: 'Saýlanan Hyzmat',
    selectStaff: 'Usgany Saýlaň',
    selectDateTime: 'Sene we Wagty Saýlaň',
    confirmBooking: '⚡ Ýazylmagy Tassyklaň',
    notifyWhatsApp: '💬 WhatsApp Bilen Habar Ber',
    notifySms: '📱 SMS Bilen Habar Ber',
    notNow: '❌ Häzir Däl',
    cancelAppointment: '❌ Ýatyrmak',
    rescheduleAppointment: '🔄 Wagt Çalşyrmak',
    pending: 'GARAŞYLÝAR',
    approved: 'TASSYKLANDY',
    completed: 'TAMAMLANYNDY',
    rejected: 'RET EDILDY',
    cancelled: 'ÝATYRYLDY',
    reschedule_requested: 'WAGT ÇALŞYRMAK ÝÜZLENMESI',
    no_show: 'GELMEDI',
    today: 'Bugün',
    tomorrow: 'Ertir',
    selectDate: '📅 Sene Saýlaň',
    language: 'Dil',
    logout: 'Ulgamdan Çyk',
    profileTitle: '👤 Müşderi Profili',
    notificationSettings: '🔔 Bildiriş Sazlamalary',
    privacyAccount: '🔒 Gizlinlik we Hasap',
    helpSupport: '💬 Kömek we Goldaw',
    closeBtn: 'Ýapmak',
    saveBtn: 'Ýatda Sakla',
    confirmTitle: 'Tassyklama',
    successTitle: 'Üstünlikli',
    errorTitle: 'Ýalňyşlyk'
  }
};

export function t(key, lang = null) {
  const activeLang = lang || detectDefaultLanguage();
  const dict = DICTIONARY[activeLang] || DICTIONARY.tr;
  return dict[key] || DICTIONARY.tr[key] || key;
}

export function autoTranslateCustomContent(text, targetLang = 'tr') {
  if (!text) return '';
  const termsMap = {
    'saç kesimi': { en: 'Haircut', ru: 'Стрижка', ar: 'قص الشعر', tk: 'Saç kesimi' },
    'sakal tıraşı': { en: 'Beard Trim', ru: 'Стрижка бороды', ar: 'حلاقة اللحية', tk: 'Sakal syrmak' },
    'ense tıraşı': { en: 'Neck Trim', ru: 'Окантовка', ar: 'حلاقة الرقبة', tk: 'Ense kesimi' },
    'saç yıkama': { en: 'Hair Wash', ru: 'Мытье головы', ar: 'غسيل الشعر', tk: 'Saç ýuwmak' },
    'cilt bakımı': { en: 'Skincare', ru: 'Уход за кожей', ar: 'العناية بالبشرة', tk: 'Yüz seretmek' },
    'vip paket': { en: 'VIP Package', ru: 'VIP Пакет', ar: 'باقة VIP', tk: 'VIP Paket' }
  };

  const lower = text.toLowerCase().trim();
  if (termsMap[lower] && termsMap[lower][targetLang]) {
    return termsMap[lower][targetLang];
  }
  return text;
}

export function getApiBaseUrl() {
  if (typeof window !== 'undefined' && window.location.hostname.includes('github.io')) {
    return 'https://ezo-stile-app.vercel.app';
  }
  return '';
}